/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package social.media.elements;

import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author Greg
 */
class ImageUtil {    
    public static ImageIcon getScaledIcon(String path, int width, int height) {
        // Load the image from the path
        ImageIcon icon = new ImageIcon(path);

        // Get the image from the icon
        Image img = icon.getImage();

        // Scale the image to the specified width and height
        Image scaledImg = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);

        // Return the new ImageIcon
        return new ImageIcon(scaledImg);
    }
}

public class PostUI extends javax.swing.JPanel {

    /**
     * Creates new form PostUI
     */
    public PostUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postHeader = new javax.swing.JPanel();
        destination = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        numPassengers = new javax.swing.JLabel();
        tripPhoto = new javax.swing.JLabel();

        destination.setText("Ski Trip Kalavrita");

        date.setText("17/2");

        numPassengers.setText("3");

        javax.swing.GroupLayout postHeaderLayout = new javax.swing.GroupLayout(postHeader);
        postHeader.setLayout(postHeaderLayout);
        postHeaderLayout.setHorizontalGroup(
            postHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(date)
                .addGap(18, 18, 18)
                .addComponent(numPassengers)
                .addContainerGap())
        );
        postHeaderLayout.setVerticalGroup(
            postHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(postHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destination)
                    .addComponent(date)
                    .addComponent(numPassengers))
                .addContainerGap())
        );

        tripPhoto.setIcon(ImageUtil.getScaledIcon("/images/ski.jpg", 367, 193));
        tripPhoto.setMaximumSize(new java.awt.Dimension(367, 193));
        tripPhoto.setMinimumSize(new java.awt.Dimension(367, 193));
        tripPhoto.setPreferredSize(new java.awt.Dimension(367, 193));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(postHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tripPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(postHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tripPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JLabel destination;
    private javax.swing.JLabel numPassengers;
    private javax.swing.JPanel postHeader;
    private javax.swing.JLabel tripPhoto;
    // End of variables declaration//GEN-END:variables
}
